version: "3.9"

services:
  database:
    image: postgres
    container_name: database_matheus
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=tsauth
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: auth
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
